import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#00687a',
        'on-tertiary-container': '#000000',
        'background': '#131313',
        'on-surface': '#e2e2e2',
        'outline-variant': '#474747',
        'on-tertiary': '#001f26',
        'on-primary-fixed-variant': '#e2e2e2',
        'on-primary-container': '#000000',
        'surface-container': '#1f1f1f',
        'tertiary-fixed-dim': '#004e5c',
        'surface-dim': '#131313',
        'on-primary-fixed': '#ffffff',
        'secondary-fixed-dim': '#a4a1ff',
        'surface-variant': '#353535',
        'primary-fixed-dim': '#454747',
        'primary-container': '#d4d4d4',
        'on-secondary-container': '#e2dfff',
        'on-error': '#690005',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary': '#0f0069',
        'on-surface-variant': '#c6c6c6',
        'on-tertiary-fixed': '#ffffff',
        'secondary-container': '#3323cc',
        'inverse-surface': '#e2e2e2',
        'on-tertiary-fixed-variant': '#acedff',
        'secondary-fixed': '#c3c0ff',
        'outline': '#919191',
        'inverse-primary': '#5d5f5f',
        'error': '#ffb4ab',
        'tertiary': '#acedff',
        'surface-container-low': '#1b1b1b',
        'secondary': '#c3c0ff',
        'primary-fixed': '#5d5f5f',
        'on-primary': '#1a1c1c',
        'on-secondary-fixed': '#0f0069',
        'surface-tint': '#c6c6c7',
        'inverse-on-surface': '#303030',
        'primary': '#ffffff',
        'on-secondary-fixed-variant': '#2606c2',
        'on-background': '#e2e2e2',
        'tertiary-container': '#009eb9',
        'surface-bright': '#393939',
        'surface-container-high': '#2a2a2a',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#353535',
        'surface': '#131313',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
